########################################################################
# Copyright (c) 1988-2016 $organization$
#
# This software is provided by the author and contributors ``as is'' 
# and any express or implied warranties, including, but not limited to, 
# the implied warranties of merchantability and fitness for a particular 
# purpose are disclaimed. In no event shall the author or contributors 
# be liable for any direct, indirect, incidental, special, exemplary, 
# or consequential damages (including, but not limited to, procurement 
# of substitute goods or services; loss of use, data, or profits; or 
# business interruption) however caused and on any theory of liability, 
# whether in contract, strict liability, or tort (including negligence 
# or otherwise) arising in any way out of the use of this software, 
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 1/2/2016
#
# Generic Gcc Makefile for talas openssl Executable
########################################################################

#
# Executable C++ .cpp sources
#
openssl_EXE_CPP_SOURCES += \
${TALAS_SRC}/talas/protocol/tls/openssl/bio_rw.cpp \
${TALAS_SRC}/talas/protocol/tls/openssl/openssl.cpp \

openssl_EXE_CPP_SOURCES += \
${TALAS_SRC}/talas/app/console/openssl/main.cpp \
${TALAS_SRC}/talas/console/main_opt.cpp \
${TALAS_SRC}/talas/console/main_main.cpp \

