########################################################################
# Copyright (c) 1988-2014 $organization$
#
# This software is provided by the author and contributors ``as is'' 
# and any express or implied warranties, including, but not limited to, 
# the implied warranties of merchantability and fitness for a particular 
# purpose are disclaimed. In no event shall the author or contributors 
# be liable for any direct, indirect, incidental, special, exemplary, 
# or consequential damages (including, but not limited to, procurement 
# of substitute goods or services; loss of use, data, or profits; or 
# business interruption) however caused and on any theory of liability, 
# whether in contract, strict liability, or tort (including negligence 
# or otherwise) arising in any way out of the use of this software, 
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 5/23/2015
#
# Generic Gcc Makefile for talas libbn Library
########################################################################

#
# user c++ flags
#
libbn_USRCXXFLAGS += \
${talas_USRCXXFLAGS} \

#
# user defines
#
libbn_USRDEFINES = \
${talas_USRDEFINES} \

#
# user includes
#
libbn_USRINCLUDES = \
${talas_USRINCLUDES} \
${talas_bn_USRINCLUDES} \

#
# user libdirs
#
libbn_USRLIBDIRS = \
${talas_USRLIBDIRS} \

#
# C .c sources
#
libbn_LIB_C_SOURCES = \
${bn_SRC}/bn_add.c \
${bn_SRC}/bn_blind.c \
${bn_SRC}/bn_div.c \
${bn_SRC}/bn_exp.c \
${bn_SRC}/bn_gcd.c \
${bn_SRC}/bn_lib.c \
${bn_SRC}/bn_mod.c \
${bn_SRC}/bn_mont.c \
${bn_SRC}/bn_mpi.c \
${bn_SRC}/bn_msb.c \
${bn_SRC}/bn_mul.c \
${bn_SRC}/bn_mulw.c \
${bn_SRC}/bn_prime.c \
${bn_SRC}/bn_randm.c \
${bn_SRC}/bn_recp.c \
${bn_SRC}/bn_shift.c \
${bn_SRC}/bn_sqr.c \
${bn_SRC}/bn_sub.c \
${bn_SRC}/bn_word.c \

#
# C++ .cxx sources
#
libbn_LIB_CXX_SOURCES = \

#
# C++ .cpp sources
#
libbn_LIB_CPP_SOURCES += \

#
# libs
#
libbn_LIBS = \

